import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";

// Import React Quill styles ở cấp độ dự án
import 'react-quill/dist/quill.snow.css';
import 'react-quill/dist/quill.bubble.css';
import { WarningSupressor } from "@/components/common/WarningSupressor";

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${inter.className} antialiased`}
      >
        <WarningSupressor />
        {children}
      </body>
    </html>
  );
}
